### ISSUE TITLE
Add samples from documentation

### ISSUE THREAD

**Issue by steffnay** [googleapis/java-datacatalog#369]
Samples exist in the Data Catalog documentation on cloud.google.com that are not present here. These samples should be added to improve their discoverability and ensure consistency across the library and the docs.

**Comment by meredithslota** [comment]
@stephaniewang526 Can you work with @steffnay on this one?

**Comment by stephaniewang526** [comment]
@steffnay i see there is an open PR -- where did those samples come from? Do we need to add more samples? Or the ones in the PR are sufficient? 

I am happy to work with @pmakani to migrate Data Catalog samples over to this repo, configure permissions, add env vars, and add ITs.

**Comment by steffnay** [comment]
@stephaniewang526 This is the issue I talked to @pmakani about. He and I had to reschedule our meeting earlier this week, but we should be able to sync up soon to clarify some details of necessary changes.

**Comment by stephaniewang526** [comment]
@steffnay sounds good! let me know if you need anything from my side.
